### ISSUE TITLE
Clean automated solution switching

### ISSUE THREAD

**Issue by miangraham** [OmniSharp/omnisharp-emacs#163]
First: Great package. Was blown away the first time I got it running and saw a proper auto-complete.

My problem: I'm having trouble cleanly switching solutions when moving between projects.

In my current setup, I'm (a) manually specifying solution files due to Unity3d projects always having  two, and (b) running a desktop setup to handle switching between multiple projects, resulting in large numbers of buffers closing and opening simultaneously.

To try and make the above play nicely with omnisharp-mode, I'm having my normal desktop switch function run the code below just before the desktop switch in order to stop the old OmniSharp server and start a new one with the solution file of the project I'm switching to, so it'll be in place before I load a few dozen omnisharp-mode buffers at once. (If I don't get the server online first, I get flooded with "Which solution file?" prompts as each buffer tries to start the server.)

This is my first attempt, which is functional but awful:

``` elisp
(defun switch-omnisharp-solution (new-solution)
  (when (get-process "Omni-Server")
    (omnisharp-stop-server)
    (while (get-process "Omni-Server") (sleep-for 0.2)))

  (omnisharp-start-omnisharp-server new-solution)

  (while (not (get-process "Omni-Server"))
    (sleep-for 0.2))
  (set-process-query-on-exit-flag (get-process "Omni-Server") nil)

  ;; This is terrible. How to get a clean hook?
  ;; Calling omnisharp--check-ready-status-worker too early locks the whole thing up.
  (message "Waiting for omnisharp server...")
  (sleep-for 10)
  (while (not (omnisharp--check-ready-status-worker))
    (sleep-for 1)))
```

The whole file, for context: https://github.com/MmmCurry/.emacs.d/blob/master/lisp/init-csharp.el

As you can see, I'm having to sleep multiple times while tearing down and restoring the server process. The one that's most bothersome is waiting for the new process to start listening for requests. Immediately calling omnisharp--check-ready-status-worker seems to block forever, so instead I'm sleeping multiple seconds to give the server time to start listening. Obviously this isn't ideal.

Questions before I start trying to patch things:
1. Am I missing an easier way to handle switching solutions in this situation?
2. If not, what's the proper way to handle cleanly waiting for the new server to come online? A hook would be nice, but having omnisharp--check-ready-status-worker handle a non-listening server would get me close enough.
3. As an alternative to waiting for the new server before proceeding, I could also try to fix the problem at the other end by, for example, having an option to tell omnisharp-mode not to auto-start the server.

Thoughts appreciated!

**Comment by nosami** [comment]
This is one of the main pain points with OmniSharp right now. I work mostly on the server side, but I have some suggestions / points.

Firstly, the server has some code for Unity solution detection and picking the correct `-csharp.sln`. I think omnisharp-emacs would need modifying to use this. The server needs starting by specifying the path to the root folder using the `-s` parameter rather than specifying the sln file.

I always meant for a separate server to be used when multiple solutions are in use. Sublime Text handles this well by maintaining a dictionary of solution files -> port number. Instead of stopping and starting the server, keeping them open might make things easier to manage.

There is a new server https://github.com/OmniSharp/omnisharp-roslyn that has a stdio/out interface. This should make it simpler to write a clean hook as the server can push events to the client (such as server ready) instead of using polling. omnisharp-emacs can't work with this interface yet. 

You should probably use the new server anyway (it also has a http interface and is compatible with the old server). It works well for Unity solutions currently.

**Comment by miangraham** [comment]
Thanks for the info! Wasn't aware of omnisharp-roslyn, I'll give it a look.

**Comment by razzmatazz** [comment]
Tracking this in https://github.com/OmniSharp/omnisharp-emacs/issues/350
