### ISSUE TITLE
Verbose option in ~/.curlrc (curl options file) borks omnisharp-build-in-emacs

### ISSUE THREAD

**Issue by egarson** [OmniSharp/omnisharp-emacs#181]
Hello,
Thank you for your fine work on omnisharp.
I was working on a shell script that uses curl heavily and put "-v" (verbose option) into ~/.curlrc (a file that curl reads and applies to all invocations). I subsequently discovered that this breaks omnisharp-build-in-emacs for reasons that are probably already obvious to you.
Kind regards
Edward

**Comment by razzmatazz** [comment]
@egarson sorry for writing this late, but have you resolve the problem already?

we have a new version of omnisharp-emacs released that does not require curl anymore and has `omnisharp-install-server` command.

I am closing this issue because this issue is rather old, please reopen if this is still a problem for you.
