### ISSUE TITLE
company-mode grouped backend complete error on empty candidates

### ISSUE THREAD

**Issue by stardiviner** [OmniSharp/omnisharp-emacs#256]
I report issue to `company-mode`, but maintainer said this issue from third extension, so I linked here.

https://github.com/company-mode/company-mode/issues/598

**Comment by razzmatazz** [comment]
@stardiviner sorry for getting to you this late;

 - can you confirm you are using 'roslyn' version of omisharp-emacs?

**Comment by stardiviner** [comment]
@razzmatazz What do you mean 'foslyn' version of omnisharp-emacs?

**Comment by razzmatazz** [comment]
@stardiviner i.e. are you using this branch:
 - https://github.com/OmniSharp/omnisharp-emacs/tree/feature-omnisharp-roslyn-support

together with
 - https://github.com/OmniSharp/omnisharp-roslyn server

This `feature-omnisharp-roslyn-support` branch is to become the next `master` version of `omnisharp-emacs` because it uses the new server from Omnisharp. Sorry for not being straightforward. I will update the documentation eventually.

**Comment by stardiviner** [comment]
I will install new version omnisharp-emacs after this branch merged to master. And try again. Then update usage info here. Can you notice me after you merged?

**Comment by razzmatazz** [comment]
okay!

**Comment by razzmatazz** [comment]
@stardiviner sorry for writing to you this late but we did have release of the new version of omnisharp-emacs that uses the omnisharp-roslyn server

please unset `omnisharp-server-path-executable` when using omnisharp-install-server command, btw

there are updated instructions on https://github.com/OmniSharp/omnisharp-emacs page

**Comment by stardiviner** [comment]
Done. Thanks
