### ISSUE TITLE
Auto-start omnisharp on opening first csharp file

### ISSUE THREAD

**Issue by alistair** [OmniSharp/omnisharp-emacs#287]

**Comment by sp3ctum** [comment]
This could work in some form. Though I remember someone complained they are restoring their Emacs session, and opening possibly tens of csharp files at the same time.

We used to have a naive implementation of this, and you might guess what it did in this case. It opened tens of omnisharp processes :smile:

**Comment by fbie** [comment]
I wrote my own clunky version of this, maybe it is of use to anyone?

```elisp
(defun find-vs-solution-upwards (dirname)
  "Recursively find first VS solution file from this directory upwards."
  (unless (or (string-empty-p dirname) (string-equal dirname "/"))
    (let ((slns (directory-files dirname 't "\\.sln$")))
      (if slns
          (car slns)
        (find-vs-solution-upwards (expand-file-name (concat (file-name-as-directory dirname) "..")))))))

(defun omnisharp-server-running? ()
  "Non-nil if there is a buffer called \"OmniServer\"."
  (get-buffer "OmniServer"))

(defun maybe-start-omnisharp ()
  "Does what it says."
  (interactive)
  (unless (omnisharp-server-running?)
    (omnisharp-start-omnisharp-server (find-vs-solution-upwards (file-name-directory (buffer-file-name))))))

(add-hook 'csharp-mode-hook 'omnisharp-mode)
(add-hook 'csharp-mode-hook 'maybe-start-omnisharp)
```

**Comment by razzmatazz** [comment]
We will definitely do this, but first we need to fix https://github.com/OmniSharp/omnisharp-emacs/issues/286 to be able to discover csproj/sln files properly based on the buffer path.

**Comment by razzmatazz** [comment]
My plan:
 - [ ] add universal param to `omnisharp-start-omnisharp-server` so we can force project file selection manually (using `read-file-name`)
 - [ ] we should track project/solution filename and base dir of the project in `omnisharp server info` assoc list (this will help to determine if buffer is managed under given server — we can have only single one running at the same time for now, but more in the future)
 - [ ] we should attempt to launch the server everytime a buffer .cs gets open
 - [ ] project file resolving algorithm when attempting to launch a server
   1. figure out available .csproj and .sln files going upwards the filesystem dir tree -> `$candidates`
   2. use .csproj if it is the single thing on the `$candidates` list (i.e. `len($candidates) == 1`)
   3. use .sln file if it is below .csproj on the `$candidates` list and `len($candidates) == 2`
   4. prompt using helm for the user to specify on of the things on the `$candidates` list, if `len($candidates) > 0`
   5. use `read-file-name` otherwise
 - [ ] a message should be shown when server is already started (as there can be only one running at the moment)
