### ISSUE TITLE
Freebsd Support

### ISSUE THREAD

**Issue by reddyBell** [OmniSharp/omnisharp-emacs#303]
Hello !

Can Omnisharp be used on FreeBSD ? I could not find any port

**Comment by razzmatazz** [comment]
Hi

I don't know if there is a port/package. But since mono does run on Freebsd, I think you can try to build [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) from source yourself. It could even be that omnisharp-mono.tgz from [omnisharp-roslyn/releases](https://github.com/OmniSharp/omnisharp-roslyn/releases) would run unmodified on mono on FreeBSD.

omnisharp-emacs port is (at least should be) OS-agnostic as it is written completely in elisp and the interface omnisharp-roslyn is JSON-based.

If this doesn't help you might want to ask guys overseeing the [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn).

**Comment by razzmatazz** [comment]
I am closing this issue then as it is not directly related to omnisharp-emacs but to omnisharp-roslyn.
