### ISSUE TITLE
omnisharp-server-executable-path

### ISSUE THREAD

**Issue by nicolas4d** [OmniSharp/omnisharp-emacs#307]
on windows

Then you need to set the omnisharp-server-executable-path the path to where you have extracted server file, e.g.:

(setq omnisharp-server-executable-path "C:\\Bin\\omnisharp-roslyn\\OmniSharp.exe")

where I put the code in? 
is the init.el?

**Comment by razzmatazz** [comment]
Yes, in init.el if you are on regular emacs. ~/.spacemacs if on spacemacs
nicolas4d <notifications@github.com> schrieb am So. 21. Mai 2017 um 19:00:

**Comment by nicolas4d** [comment]
I put the code in init.el, first. but it was'nt work.
after that I put the code in the .emacs, it worked , how explan this.

**Comment by razzmatazz** [comment]
@nicolas4d where is your init.el? windows probably uses special path to resolve init.el, and fallbacks to .emacs if .emacs.d/init.el not found, check this (though I am not sure if the information on this page is up to date):
 - https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Location-of-init-file.html

otherwise, please close the issue if it is working for you now..

**Comment by razzmatazz** [comment]
@nicolas4d could you try the new `M-x omnisharp-install-server` command which should be available on Windows now (with the latest package from melpa)

you should remove (setq omnisharp-server-executable-path) from your init.el when using `omnisharp-install-server`

**Comment by razzmatazz** [comment]
closing this as there has been no response for a longer time, @nicolas4d please reopen if this is still valid issue for you
