### ISSUE TITLE
Symble's function definition is void : omnisharp--path-to-server

### ISSUE THREAD

**Issue by nicolas4d** [OmniSharp/omnisharp-emacs#308]
it happpends like title when i type M+x omnisharp-start-omnisharp-server and select a diretory

**Comment by razzmatazz** [comment]
hi @nicolas4d 

sorry for getting to this late, but can you tell a little bit about your setup?

 - have you upgraded from older version (non-roslyn) or is this a plain new installation (i.e. since 2017-04-xx)
 - spacemacs? regular emacs?
 - have you installed omnisharp-emacs package from melpa or from source?
 - windows/linux/mac/unix?
 - emacs version?
 - could you check if omnisharp.el file has `(require 'omnisharp-utils)` line ? and if so, is "omnisharp--path-to-server" visible when you do M-x describe-function and then look for omnisharp--path-to-server?

**Comment by aleksandr-skobelev-epam** [comment]
I have the similar problem.
* This is a fresh installation.
* This is a plain Emacs 25.1 (9.0) on MacOS installed with Homebrew.
* Omnisharp-emacs was installed from melpa.
* omnisharp.el has (require 'omnisharp-utils) line. But M-x describe-function can not find omnisharp--path-to-server.
* If you open some C# file (i.e load omnisharp-mode) this problem dissappears.

**Comment by razzmatazz** [comment]
ok, I replicated this myself.. taking look at this atm

**Comment by razzmatazz** [comment]
I will keep this reopen so @aleksandr-skobelev-epam and @nicolas4d can confirm this works after the update/fix is on melpa.

**Comment by razzmatazz** [comment]
the fix works for me after reloading updated package from melpa; please reopen if this doesn't work for you

**Comment by aleksandr-skobelev-epam** [comment]
Sorry for the delay with feedback. The issue was fixed in my configuration also. Thanks a lot!
