### ISSUE TITLE
omnisharp-20190422.748 displays *omnisharp-log* single/multi line debug to show up in minibuffer

### ISSUE THREAD

**Issue by ijacquez** [OmniSharp/omnisharp-emacs#481]
If I move the cursor over a variable, the minibuffer enlarges to nearly half the screen and displays parts of the `*omnisharp-log*` file.

I tried setting `omnisharp-debug` to `nil` via `setq` and it doesn't seem to take any effect.

I'm able to avoid having it resized by setting `resize-mini-windows` from `grow` to `nil`. However, I still see output.

**Comment by ijacquez** [comment]
I found that if I move back to Omnisharp server v1.32.6 via `(setq omnisharp-expected-server-version "1.32.6")`, then this issue doesn't occur.

I skipped over to *v1.32.18* and nothing works (separate issue), including `omnisharp-debug`.

**Comment by razzmatazz** [comment]
Hi @ijacquez . Sorry for replying after such a long time.

I have hard time imaging myself what could be causing the issue. Do you have a screenshot? What content is shown on the log?

This is apparently related to server version, since you said reverting to v1.32.6 causes all the symptoms to disappear, right?

**Comment by ijacquez** [comment]
No worries. Thanks for getting back to me. I actually moved on, and went with Doom Emacs and forgot about it. I'm running _v1.32.18_ now and the problem has disappeared.

Closing.
